# Generated by Django 4.2.7 on 2025-02-24 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_content_remove_teahistory_tea_garden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tea_images/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='teagarden',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teagarden',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tea_garden_images/'),
        ),
        migrations.AddField(
            model_name='teahistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tea_history_images/'),
        ),
    ]
